# Generated by Django 3.2.16 on 2023-01-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('channel', models.CharField(blank=True, max_length=250, null=True, verbose_name='Канал')),
                ('id_bothelp', models.CharField(blank=True, max_length=250, null=True, verbose_name='ID BotHelp')),
                ('id_telegram', models.CharField(blank=True, max_length=250, null=True, verbose_name='ID Телеграм')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Фамилия')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=250, null=True, verbose_name='Телефон')),
                ('link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка')),
                ('utm_source', models.CharField(blank=True, max_length=250, null=True, verbose_name='utm_source')),
                ('utm_campaign', models.CharField(blank=True, max_length=250, null=True, verbose_name='utm_campaign')),
                ('utm_medium', models.CharField(blank=True, max_length=250, null=True, verbose_name='utm_medium')),
                ('utm_term', models.CharField(blank=True, max_length=250, null=True, verbose_name='utm_term')),
                ('utm_content', models.CharField(blank=True, max_length=250, null=True, verbose_name='utm_content')),
                ('unsubscribed', models.DateTimeField(blank=True, null=True, verbose_name='Отписался')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Телеграм',
                'verbose_name_plural': 'Телеграм',
            },
        ),
        migrations.CreateModel(
            name='BotUtmLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Пригласительная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Ссылки',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
